title: Debabrata Ghosh
description: Tech lead of testing team | Learning codings on Artificial Intelligence and Machine Learning
<center><img src="assets/css/SelfImage.jpg"/></center>
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
